jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/shark8me/demucs.git
  demucs:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        sudo apt-get -y install soundstretch
        pip install -r requirements.txt
        python3 --version
      image: tensorflow/tensorflow:1.14.0-gpu-py3
