on:
  push:
    branches:
      - main

name: Build and Deploy a Container
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  API_SERVICE_VERSION: v0.1
  DEMUCS_IMAGE: gcr.io/${{secrets.GCP_PROJECT}}/demucs-trainer:v0.1
  REGION: us-east1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY}}"

    - name: "Set up Cloud SDK"
      uses: "google-github-actions/setup-gcloud@v1"

    - name: "Use gcloud CLI"
      run: "gcloud info"

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push http container
      run: |-
        docker build -t ${{ env.DEMUCS_IMAGE }} .
        docker push ${{ env.DEMUCS_IMAGE }}
